theme: jekyll-theme-cayman
# Site settings
title: 赵会军个人博客                     #你博客的标题
SEOTitle: 赵会军个人博客        #显示在浏览器上搜索的时候显示的标题
header-img: img/post-bg-rwd.jpg     #显示在首页的背景图片
email: huijun_zhao86@163.com    
description: "赵会军个人博客"              #网站介绍
keyword: "赵会军个人博客,Java,Spring,SpringMVC,MyBatis,Dubbo,Spring Cloud,Redis,MySQL" #关键词
url: "https://zhaovincent.github.io"          # 这个就是填写你的博客地址
baseurl: ""      # 这个我们不用填写
